import type { Product } from "@/components/store/product-card";

/**
 * 商店示例数据
 *
 * 在真实接入 @lynxkit/api-client 的 StoreApi 之前作为占位。
 * 后续切换为 storeApi.list() 返回。
 */
export const STORE_PRODUCTS: Product[] = [
  {
    id: "ai-companion-chat",
    name: "AI 陪伴聊天",
    description: "基于 GPT-4 与 pgvector 的角色扮演陪伴应用，支持长记忆与多角色切换。",
    thumbnail: "",
    price: 9900,
    rating: 4.9,
    downloads: 1248,
    category: "AI 社交",
    creator: { name: "陈思远" },
    tags: ["热门", "GPT-4"],
  },
  {
    id: "mini-crm",
    name: "轻量 CRM",
    description: "面向小微企业的客户管理后台，开箱即用的客户、商机、合同管理。",
    thumbnail: "",
    price: 19900,
    rating: 4.7,
    downloads: 856,
    category: "AI 管理后台",
    creator: { name: "Linda Wang" },
    tags: ["团队"],
  },
  {
    id: "smart-bi",
    name: "智能 BI 报表",
    description: "自然语言生成 SQL 与图表，企业级数据洞察平台，支持多数据源接入。",
    thumbnail: "",
    price: 29900,
    rating: 4.8,
    downloads: 624,
    category: "AI 数据分析",
    creator: { name: "张明" },
    tags: ["企业"],
  },
  {
    id: "content-publish",
    name: "内容发布平台",
    description: "多渠道内容一键分发，支持公众号、视频号、小红书等平台的定时发布。",
    thumbnail: "",
    price: 0,
    rating: 4.6,
    downloads: 2310,
    category: "AI 营销",
    creator: { name: "Alex Chen" },
    tags: ["免费"],
  },
  {
    id: "booking-app",
    name: "预约服务 App",
    description: "美容、医疗、教培等行业的预约小程序，支持多门店与员工排班。",
    thumbnail: "",
    price: 14900,
    rating: 4.5,
    downloads: 412,
    category: "AI 应用 App",
    creator: { name: "王芳" },
  },
  {
    id: "smart-iot-hub",
    name: "智能家居中枢",
    description: "对接 HomeAssistant 与本地 MQTT 的 IoT 控制面板，支持自定义场景编排。",
    thumbnail: "",
    price: 39900,
    rating: 4.9,
    downloads: 198,
    category: "AI 硬件",
    creator: { name: "Mike Liu" },
    tags: ["硬件"],
  },
  {
    id: "knowledge-base",
    name: "AI 知识库",
    description: "团队文档智能问答平台，支持 Markdown 与 PDF 上传、自动向量检索。",
    thumbnail: "",
    price: 9900,
    rating: 4.7,
    downloads: 1843,
    category: "AI 工作站",
    creator: { name: "Sophie" },
    tags: ["团队"],
  },
  {
    id: "social-match",
    name: "AI 匹配社交",
    description: "基于性格与兴趣图谱的智能匹配应用，支持实时聊天与语音通话。",
    thumbnail: "",
    price: 0,
    rating: 4.8,
    downloads: 5230,
    category: "AI 社交",
    creator: { name: "周杰" },
    tags: ["免费", "热门"],
  },
  {
    id: "auto-platform",
    name: "自动化平台",
    description: "工作流自动化中台，可视化拖拽编排，连接 200+ 应用与服务。",
    thumbnail: "",
    price: 49900,
    rating: 4.6,
    downloads: 387,
    category: "AI 系统",
    creator: { name: "Vincent" },
    tags: ["企业"],
  },
];

export const STORE_CATEGORIES = [
  { slug: "all", name: "全部" },
  { slug: "AI 社交", name: "AI 社交" },
  { slug: "AI 系统", name: "AI 系统" },
  { slug: "AI 工作站", name: "AI 工作站" },
  { slug: "AI 数据分析", name: "AI 数据分析" },
  { slug: "AI 管理后台", name: "AI 管理后台" },
  { slug: "AI 应用 App", name: "AI 应用 App" },
  { slug: "AI 营销", name: "AI 营销" },
  { slug: "AI 硬件", name: "AI 硬件" },
];
